# Generated by Django 4.2.2 on 2023-06-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vunoklang_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorialmembers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='editorialmembers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='editorialmembers',
            name='institution',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='editorialmembers',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
